### ISSUE TITLE
Name of app shows up instead of collection name at the start

### ISSUE THREAD

**Issue by callingmybluff** [etesync/etesync-notes#1]
**Expected**

The top bar shows the name of current collection.

**Current behaviour**

Upon starting the app, the name of the app shows up on the top bar instead of the name of collection. One would have to go to collections and check what one is actually selected.

**Comment by tasn** [comment]
It shows all of the notebooks combined by default, so it needs a generic title. We could change it to "All Notes", though I think the name of the app is better, no?

**Comment by callingmybluff** [comment]
That would be perfect, thanks!
