### ISSUE TITLE
Focus is lost in browsers when moving the cursor past the edges of a note

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/etesync-notes#10]
Sorry for the weird title, I'm a bit unsure on how to explain the issue.
Whenever the cursor moves past the edge of a note, making the application scroll up or down, it loses focus (both in Chromium and FF).

The easiest way of encountering this issue is by creating a note that fills the entire length of the screen, and then pressing enter for a new line. The application scrolls down (the topmost line goes off-screen), the new line is visible and the focus is lost.

A video demonstrating it (I made my FF window smaller to demonstrate it more easily):

![bug](https://user-images.githubusercontent.com/19950793/95313888-f09bfe80-0890-11eb-98fc-5940bb1f93bf.gif)

I accidentally cut off a bit of the bottom part, that's my fault.

**Comment by tasn** [comment]
Does it happen for you in the apps too? Thanks for the report, seems to be something wrong with how it's done in the web client.

Also, looking at what you showed, the padding seems to be off for those last two lines, or is it just because the rest is manually indented?

**Comment by Salt-Factory** [comment]
The rest is manually indented from the copy-paste where I got it. :-) 
I can't try it in the app because of issue #11.
