### ISSUE TITLE
BLANK WHITE SCREEN

### ISSUE THREAD

**Issue by bobleeSwagger2** [etesync/etesync-notes#114]
latest update (1.6.??) has made the app unusable on both iOS and Android. Initial splash screen shows logo, then blank white screen. Please fix asap
*edit- FYI this is on iOS 14 and Android 11. Tried to downgrade on Android to previous version but build was corrupt (f-droid) if any other info needed, let me know

**Comment by tasn** [comment]
Can you provide more information? Can you maybe try uninstalling on Android and then trying to install an older version from f-droid? (you can't just install an old version on top of a new one on Android)

**Comment by bobleeSwagger2** [comment]
Haha that’s actually what I meant I did Tom. I uninstalled, tried to install an older version but it wouldn’t install (corrupt). I reinstalled the latest version, logged in and all was fine. In settings, I downloaded latest update manually and boom! Blank white screen. On iOS i can’t do anything obviously

**Comment by tasn** [comment]
Ah, it's my fault, I know what's up. Sec, fixing.

**Comment by tasn** [comment]
Should now be fixed. Try reistalling the Android app.

**Comment by bobleeSwagger2** [comment]
Yessir that fixed it. What about iOS?

**Comment by tasn** [comment]
Yay! Sorry about that!
