### ISSUE TITLE
Note is sometimes pushed when still editing in web browser

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/etesync-notes#13]
Periodically, the client pushes to the server whilst in the middle of editing.
This results in a loss of focus on the editor.

**Comment by Salt-Factory** [comment]
Update: on Chromium this resulted in loss of focus, but in FF this puts me back on the note overview page.
I then have to manually reopen the note in order to continue editing, breaking my train of thoughts.

**Comment by tasn** [comment]
Note to self: the problem, I believe, is that the automatic background sync is triggering so it's pushing the time you are working on. This shouldn't happen. I'll figure out how to solve this.
