### ISSUE TITLE
Note deletion doesn't propagate

### ISSUE THREAD

**Issue by maxf** [etesync/etesync-notes#132]
Using 2 instances of Etesync notes on 2 Android devices, and the webapp

While editing a note on 1 device syncs normally with the others, deleting a note doesn't.
The deleted note is gone one the device where it was erased, but it's still there on the other devices.

**Comment by tasn** [comment]
I can't test at the moment (sorry!), but I tested it before and I'm 100% sure it at least used to work for me. @zecakeh, have you encountered any issues there? Did we even change something related that may cause a regression?

**Comment by zecakeh** [comment]
Actually I noticed that same problem today. I'm not sure what caused that regression but I'll have to investigate.

**Comment by zecakeh** [comment]
I went back to v1.4.0 and it doesn't work… The feature was introduced in 1.3.1 but I can't login on that version.

None of the code involved seems to have changed since it's been introduced and looking at it I can see it updating the local cache, but not syncing the changes with the server.

**Comment by tasn** [comment]
@maxf, could you please open the app and go to settings -> scroll all the way down -> download updates? This will let you try the latest version. Could you then check whether it fixes it for you?

Thanks @zecakeh for fixing this!

**Comment by maxf** [comment]
Yep. I've logged out of the 3 instances I had opened, logged back in and it now all synchronises nicely. Thanks!
BTW, the android app still crashes when switching to passowrd manager when logging in (Android 11), as I reported by email earlier.

**Comment by tasn** [comment]
Yay! Can you please open another ticket for the crash? Thanks!
