### ISSUE TITLE
Android 11: crash when switching to password manager to login and switching back to Notes

### ISSUE THREAD

**Issue by maxf** [etesync/etesync-notes#138]
Logged out of etesync notes, tried to log in again, switched to password manager app to copy password. Went back to etesync and got this:

{"version":"1.7.0","error":{"message":"null is not an object (evaluating 'n.getCollectionManager')","stack":"index.android.bundle:1046:2418\ny@index.android.bundle:112:587\nindex.android.bundle:112:1890\ny@index.android.bundle:112:587\no@index.android.bundle:112:1066\nindex.android.bundle:112:1209\nf@index.android.bundle:128:155\nindex.android.bundle:128:864\ny@index.android.bundle:133:581\nC@index.android.bundle:133:947\ncallImmediates@index.android.bundle:133:3004\nvalue@index.android.bundle:28:2919\nindex.android.bundle:28:1095\nvalue@index.android.bundle:28:2611\nvalue@index.android.bundle:28:1065\nvalue@[native code]\nvalue@[native code]","logs":""}}

**Comment by tasn** [comment]
@zecakeh, I suspect this may be related to your recent changes in how navigation works. Any thoughts?
