### ISSUE TITLE
Can You Access EteSync Notes In Apple Notes App?

### ISSUE THREAD

**Issue by trymeouteh** [etesync/etesync-notes#14]
Or is the only way to access EteSync Notes on a iPhone is in the EteSync Notes app?

**Comment by tasn** [comment]
Only way is the EteSync Notes app. There's no way to sync with the Apple notes app on iOS even if we wanted. We are going to have a much better app than the Apple notes anyway (for example, we have rich text support), so very soon they would be largely incompatible anyway, even if we could share them.
