### ISSUE TITLE
Consistently Crashes When Clicking Three Dots

### ISSUE THREAD

**Issue by Zakkumaru** [etesync/etesync-notes#167]
On the main screen, when you click the three dots in the upper-right corner, it crashes 100% of the time, goes to the splash screen with the login, and freezes.  I don't even know what the three dots do, at this point.

**Comment by Zakkumaru** [comment]
The in-app debugger gives this message each time:
```
[I] ConnectionfInfo: true wifi
```

**Comment by zecakeh** [comment]
What platform are you on?

**Comment by Zakkumaru** [comment]
> What platform are you on?

I'm not sure I understand.  I thought this was an Android app?

**Comment by zecakeh** [comment]
It's available on Android, iOS and Web 😉

What version of Android are you using? Did you install the app from the Play Store or F-Droid?

**Comment by Zakkumaru** [comment]
I'm using LOS17.1, and I installed it from F-Droid.

**Comment by zecakeh** [comment]
OK so a lot has changed since then and sadly the latest version isn't available on F-Droid. We even plan to release a new version soon. You'd have to test this with the latest version to see if the bug is still there before we start to investigate.

**Comment by Zakkumaru** [comment]
Doing local builds of any of TAsn's apps is always a lot of work, so I might just have to wait.  Haha

**Comment by tasn** [comment]
> Doing local builds of any of TAsn's apps is always a lot of work, so I might just have to wait. Haha

Haha, sorry. :P 

As @zecakeh said, we plan on having a new version soon, I'm just super busy so haven't had the time to review all of the patches yet. :(

**Comment by Zakkumaru** [comment]
Fixed I'm newer versions.
