### ISSUE TITLE
Is the notes data encrypted at rest?

### ISSUE THREAD

**Issue by gitbq** [etesync/etesync-notes#170]
Hi Devs

Are the notes encrypted at rest at your end - assuming I'm not self hosting?
When using the android app, are the notes also encrypted at rest?

Apologies if this is addressed elsewhere but I couldn't track anything down. 
Thanks again

**Comment by tasn** [comment]
Hey, its end-to-end encrypted, which is a stronger promise than encryption at rest! The data is encrypted or your device, and never leaves in unencrypted. With encryption at rest, the service provider can access your data, we can't!

Anyhow, this is not an issue with this repo, please ask on reddit if you have any more questions: https://www.reddit.com/r/EteSync/
