### ISSUE TITLE
Is EteSync Notes dead?

### ISSUE THREAD

**Issue by catwithbanana** [etesync/etesync-notes#192]
There hasn't been a release in 18 months and no issue has been closed in over a year. I would love the updates [outlined in this blog post](https://blog.etesync.com/guest-post-improving-etesync-notes/) to come to fruition, but there hasn't been any recent activity. Is EteSync Notes dead?

**Comment by tasn** [comment]
Not dead, it's just that I've been super busy, and the other main developer has been traveling, and I guess no longer active.

**Comment by embamba** [comment]
But you're taking our money, anyway? Hmm. I've gotten good use out of this, even with the OS X problems. I wish I'd realized it's been largely abandoned. I'd likely have cancelled before my last payment. Thanks for this while it lasted and I hope things go well for you in the future.

**Comment by tasn** [comment]
> But you're taking our money, anyway?

I don't understand this sentiment. If you decided to pay for a product that you just say "you've gotten good use of" and still works well, what's the problem?

**Comment by tasn** [comment]
Anyhow, I'm closing this ticket because the question has already been addressed.
