### ISSUE TITLE
Feature Request: export option

### ISSUE THREAD

**Issue by lord-aerion** [etesync/etesync-notes#20]
It would be useful to have an option to export notes, whether as plain text, HTML or PDF.

In Android terms I guess this is treated as a share action, but I'm using the term export here to avoid confusion with sharing of notes with EteSync Associate accounts.

**Comment by sdeleuze** [comment]
Yeah +1 on that one, that's especially important to avoid data loss (would probably require an import option as well).

**Comment by sdeleuze** [comment]
#24 is probably a duplicate of this one, and provides IMO a more detailed description about why this is important. Maybe this one should be closed?

**Comment by tasn** [comment]
Closed in favour of #24.
