### ISSUE TITLE
Cursor shifts when editing text inputs in dialogs

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/etesync-notes#25]
Sorry for the odd title again.

Basically, when trying to make a new note or editing the name of an existing note in the Android app, the behaviour of the cursor on backspace has an issue.
Deleting the last letter of the name works just fine, but when tapping backspace when the cursor is anywhere else will delete the correct letter, and then shift the cursor over one letter.

Per example (with `|` representing the location of the cursor):

`Cool nate name|` -> backspace results in `Cool nate nam|`
`Cool na|te name` -> backspace results in `Cool |nte name`

The same happens when trying to type anything in the middle.

`Cool n|te name` -> adding an o results in `Cool |note name`.

It types out the o, and then immediately shift one character to the left.

I am using the Android app, v1.3.1

**Comment by tasn** [comment]
I just tested it, and I can verify it happens here too. What the heck. :)

**Comment by tasn** [comment]
I changed the title, because I now see it's just related to dialogs... I bet I also know why, because I think dialogs are a hack around the render loop in react, so they delay one render loop which causes the cursor movement to happen one loop too late.
