### ISSUE TITLE
Feature Request: option to default to view mode

### ISSUE THREAD

**Issue by lord-aerion** [etesync/etesync-notes#28]
I tend to want to open existing notes in view mode more often than edit mode. This means I'd prefer to see the rendered version as the applied formatting makes the note easier to read.

A good example would be recipes. Once added they're unlikely to change, and when opening a recipe it will almost always be to follow it, not to modify it. Formatting like bullet lists, headers, font size. etc. greatly enhance the legibility of recipes while cooking.

A toggle for the preferred mode in the settings would be great to have.

**Comment by tasn** [comment]
It's already there. It just opens the last view mode you used... Is it not working for you?

I'm closing it as I believe it's fixed already, but let me know if it isn't.

**Comment by lord-aerion** [comment]
I wasn't aware that it uses the last mode used. Just tested that, and that works as designed.

That's not quite the same as being able to set a preferred mode though. If I was last in edit mode then that means my example of a recipe would open in edit mode, thus requiring an additional action to get back to view mode. Being able to set a preferred mode gives each user the choice of what works best for them.

**Comment by tasn** [comment]
Fair enough, re-opening.
