### ISSUE TITLE
Ordered and unordered lists not wrapping at edge of screen.

### ISSUE THREAD

**Issue by shompoe** [etesync/etesync-notes#36]
List items in preview mode that run off the edge of the screen are not wrapping onto the next line, and there is a blank space where the wrapped text ought to be.

![Screenshot-2020-10-20-22-04-32](https://user-images.githubusercontent.com/54352351/96644037-5e7c0780-1320-11eb-8dee-1fb8a76f255c.jpeg)

**Comment by tasn** [comment]
I also got reports of linens getting merged together. It's probably because we just updated our `react-native-markdown-display` dependency.

**Comment by andreasmjg** [comment]
I have the same issue

**Comment by Eryc-M** [comment]
I am having the same issue as the image shows (on Android and iOS); word wrapping and line spacing issues. 
Android eteSync Notes version 1.5 
iOS eteSync Notes version 1.4.1

**Comment by geovie** [comment]
Updating to the latest alpha of react-native-markdown-display should fix this: https://github.com/iamacup/react-native-markdown-display/issues/120

**Comment by tasn** [comment]
Thanks @geovie, will fix now!
