### ISSUE TITLE
Android fails with Network error

### ISSUE THREAD

**Issue by smarkars** [etesync/etesync-notes#43]
![Screenshot_20201029-194713](https://user-images.githubusercontent.com/2861608/97586106-e1d3e200-1a1f-11eb-8e36-b2546cb35400.jpg)

In Android not able to login and logs also not generated under the settings. But there is no issue with iOS app. Running the server from the master branch in debug mode in a local osx machine. Server not getting hit from the app also. 

For eg by local setup of server running at http://192.168.1.104:7000

**Comment by tasn** [comment]
I think it's because you are not using `https`. Android is blocking non-https calls by default, and maybe we haven't enabled that. Though if I may suggest: use HTTPS. Certs are very easy to get and you are putting yourself at risk by not using it. Even though the data is end-to-end encrypted, the access tokens (to just manipulate the data on the server) aren't.

I'm on the fence whether it's a good idea or not to even allow http connections.

**Comment by smarkars** [comment]
Thanks!

I will try that. But the Ete Sync app is working fine without any issues in
Android with the same server. So it looks like that sync app allows http
and notes doesn't!

**Comment by tasn** [comment]
That's very well possible. The sync app has been around for a long time, while the notes app is new.

**Comment by smarkars** [comment]
I'm sorry to bother you again. I'm an iOS dev not good at Android. But as
far as I know I don't think Android supports self signed certificate.

So is there is any workaround for this? I would like to run sync server in
home in a Pi (behind a NAT network, so no public IP) and when I'm out I
could access the server using a VPN connection. If I use a self signed
certificate still this may not work correct?

Thanks for your help!

**Comment by tasn** [comment]
I think I'm convinced, I'll add the exception to Android. Please follow up with me on Sunday if I haven't done it by then, and I'll make sure to do it.

**Comment by smarkars** [comment]
> I think I'm convinced, I'll add the exception to Android. Please follow up with me on Sunday if I haven't done it by then, and I'll make sure to do it.

I don't see a new commit on this. Thought I could remind you! Thanks!

**Comment by tasn** [comment]
Done. Are you able to test an apk if I upload one? Or should I just make a release and hope it's indeed fixed for you?

**Comment by tasn** [comment]
Released a new version with the fix.
