### ISSUE TITLE
Screen-filling technical message after login

### ISSUE THREAD

**Issue by c7hm4r** [etesync/etesync-notes#44]
When trying to log in to my personal EteSync server, this screen is displayed after pressing the "LOG IN" button:

<img src="https://user-images.githubusercontent.com/1974041/97732693-31c1b000-1ad7-11eb-8151-1e10a4de8807.png" alt="Screenshot_20201030-173032_EteSync_Notes" width="400"/>

Pressing the Android back button exits the app. Reopening the app shows the login screen again.

This prevents me from using the app entirely.

The debug log does not contain any specific information.

#### Setup

- Android 10 (Lineage)
- App version: 1.4.4 (F-Droid)
- The Internet was available on my Android system.
- The EteSync app works properly.
- Server version: https://github.com/etesync/server/commit/46abeac2c051050d5400238347cf6c11008fc91b (2020-10-30)

**Comment by tasn** [comment]
First of all, you are running your server in debug mode, you probably shouldn't. :)
This is debug output from the server...

As for the issue at hand: try checking your server's output, it'll probably contain useful information. If not, please consider joining us at https://www.etesync.com/community-chat/ for help from the rest of the community (not everyone is scouting tickets).

There is an issue with the notes app though, it should probably make this error message scrollable.
