### ISSUE TITLE
No padding in edit mode

### ISSUE THREAD

**Issue by sdeleuze** [etesync/etesync-notes#47]
The lack of padding in edit mode makes it pretty difficult to go at the beginning of a line on iOS, and makes the cursor position/first letter difficult to see in the webapp.

![image](https://user-images.githubusercontent.com/141109/98448114-39620400-212a-11eb-824a-8f990d87c1a1.png)

**Comment by tasn** [comment]
There is padding in edit mode (10px wide). Could you please try opening the notes app in incognito mode to make sure you have the latest version and it's not just a cache issue?

**Comment by sdeleuze** [comment]
I opened the app in incognito mode, but the issue is the same, and it also impact the mobile app on iPhone.
I am using Brave (so Chrome based).

If that can help, see below a screen capture with devtools in view mode where I can see the padding:
![image](https://user-images.githubusercontent.com/141109/98461380-ef216700-21ab-11eb-9411-043a59371bf9.png)

But in edit mode you can see that not padding seems to be defined:
![image](https://user-images.githubusercontent.com/141109/98461353-be413200-21ab-11eb-9adf-47b7e58a0eb1.png)

**Comment by tasn** [comment]
Oops, you are right. it's a recent regression and I just haven't noticed it on Android as there's already decent padding there by default.

**Comment by tasn** [comment]
Just deployed a new version.

**Comment by sdeleuze** [comment]
Thanks for the quick fix.

**Comment by tasn** [comment]
Does it indeed work (on the web)?

**Comment by sdeleuze** [comment]
Yeah there is now left and right padding on the webapp, thanks.

![image](https://user-images.githubusercontent.com/141109/98464764-37994e80-21c5-11eb-8089-4f8069407a83.png)

May I suggest to specify a top and bottom `10px` padding as well? That would be consistent with the view mode, would look IMO better and I am not sure the current `0px` is defined on purpose.

**Comment by tasn** [comment]
Fixed that one too. Thanks!
The confusing thing is that on Android (where I'm testing) there is default padding, so I didn't notice it. :)
