### ISSUE TITLE
Remove the + in note creation screen

### ISSUE THREAD

**Issue by Zybque** [etesync/etesync-notes#48]
Hi!
While creating a note in the android app  the "+" hovers in front of the "ok" button when the keyboard is out. I expect more people to have this -I am using a pretty standard phone. I think one could easily remove the "+" as it's not really necessary in this screen.

![Screenshot_20201115-045650](https://user-images.githubusercontent.com/74480960/99162733-2d191080-2701-11eb-88b2-e5d94caa6ec1.png)

**Comment by tasn** [comment]
Ah, it's a regression because of our fix with the text being wrong. Yup, it should either be removed or at the very least hide behind the dialog.
