### ISSUE TITLE
Move plus sign to top when on web interface

### ISSUE THREAD

**Issue by andreasmjg** [etesync/etesync-notes#52]
Hi, if I have 20-30 notes and want to create a new one on laptop, I need to scroll down to the bottom each time which is a bit cumbersome.

Maybe better to move plus sign to the top of the screen (part of yellow strip?) and make this "sticky" at the top of the web UI?

See example of problem here (on high-res screen, too, 1900 x something): 
[screenshot](https://i.ibb.co/WVmyDLk/Screenshot-from-2020-11-22-14-16-34.png)

**Comment by tasn** [comment]
Hmm, this is a bug, it should definitely be floating and not scroll, even with many notes.
