### ISSUE TITLE
Some UI improvements on web interface

### ISSUE THREAD

**Issue by andreasmjg** [etesync/etesync-notes#53]
Hi, a few UI improvements:

1) If I have 20-30 notes and want to create a new one on laptop, I need to scroll down to the bottom each time which is a bit cumbersome.

Maybe better to move plus sign to the top of the screen (part of yellow strip?) and make this "sticky" at the top of the web UI?

See example of problem here (on high-res screen, too, 1900 x something): 
[screenshot](https://i.ibb.co/WVmyDLk/Screenshot-from-2020-11-22-14-16-34.png)

2) Pop-up after creating notes not visible when scrolled to bottom

* Have a lot of notes
* Scroll to bottom to click blue plus button

==> I can't see the pop-up coming up to select where to put note & name the note without scrolling up again

 
3) Screen jumping around when selecting notebook

* Have a lot of notes
* Scroll to the bottom to click blue plus button
* Scroll up again to see the selection box
* Give your note a name
* Click to select notebook

==> Scrolls up to the top and open a window "nowhere" (see [screenshot](https://i.ibb.co/82qf41d/Screenshot-from-2020-11-22-14-27-33.png) )

* Then after selection of where to put the note, it jumps down to the selection box again.

4) Not alt-tab friendly

* Have a lot of notes
* Scroll to the bottom to click blue plus button
* Scroll up again to see the selection box where you give name to the note and select where to put the note
* Alt-tab to another window while keeping the selection box open
* Alt-tab back

==> Window is at the top (see orange top selector) and I need to scroll down again to give my note a name

5) In selection box where you give a note a name, pressing "enter" after giving the note a Name should either (a) save the name and open the note for editing, or (b) open the selector box for where to put the note. Currently nothing happens when pressing enter

**Comment by zecakeh** [comment]
1-4 should be fixed by now, there's only 5 left.
