### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by shompoe** [etesync/etesync-notes#7]
There is a whole line space between list items. Other markdown implementations do not have any extra spacing between individual list items.

Eg.

* dhdhshdhdh
* fjfjfhfhh
* fjdhdhdhdh

1. dhdhgdh
2. dhdhdhdhdh

**Comment by tasn** [comment]
Not sure I follow, where is the whole line space, in the rendering? Could you please elaborate more on what's wrong, how to reproduce it, and how it should be? Thanks!

**Comment by shompoe** [comment]
Oh, ok.

Yes, in the rendering.   So when you switch from edit to view mode the lists are very gappy. I think the usual rendering for this is just normal line spacing. 

![Screenshot-2020-10-06-19-07-46](https://user-images.githubusercontent.com/54352351/95242574-44620580-0807-11eb-8f43-9b222845151c.jpeg)

**Comment by tasn** [comment]
Yup, definitely wrong. I'll have to take a look into this, thanks!
