### ISSUE TITLE
App crash when creating a notebook

### ISSUE THREAD

**Issue by r4nd0m123** [etesync/etesync-notes#73]
Hi,

I'm running EteSync Notes on a Pixel 3 which is running [GrapheneOS](https://grapheneos.org/). When I try to create my first notebook the app immediately crashes. After the crash and restarting the app I can see the following logs within the app.

[C] TypeError: undefined is not an object (evaluating 'o.name')
[D] App switched to foreground
[I] ConnectionfInfo: true wifi
[C] TypeError: undefined is not an object (evaluating 'o.name')
[D] App switched to foreground
[I] ConnectionfInfo: true wifi
[D] App switched to background
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[I] ConnectionfInfo: true wifi
[C] TypeError: undefined is not an object (evaluating 'o.name')
[D] App switched to foreground
[I] ConnectionfInfo: true cellular
[C] TypeError: undefined is not an object (evaluating 'o.name')
[D] App switched to foreground
[I] ConnectionfInfo: true cellular
[D] App switched to background
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[I] ConnectionfInfo: true wifi
[C] TypeError: undefined is not an object (evaluating 'o.name')
[D] App switched to foreground
[I] ConnectionfInfo: true wifi

I could take a logcat and share it privately if needed.

**Comment by tasn** [comment]
This is very weird. What happens if you logout and log back in?

**Comment by r4nd0m123** [comment]
> This is very weird. What happens if you logout and log back in?

Doh. That fixed it.
