### ISSUE TITLE
Feature request: Search notes

### ISSUE THREAD

**Issue by shompoe** [etesync/etesync-notes#8]
Hi Tom,

You didn't mention searching notes in the "roadmap" of features you are planning.

**Comment by tasn** [comment]
Was an oversight in the blog post. We also plan on having that. Thanks for opening this ticket!

**Comment by tasn** [comment]
Note to self: I forgot the name of the library at the moment, but we should use the proper search library that also does fuzzy searching and etc.
Implementing searching in notes is not that hard. What's going to be annoying is building the interface to show the results. :)

**Comment by zecakeh** [comment]
With the content of the notes encrypted even in cache, we need to decrypt them first. Won't that make search slow, especially when there's a lot of notes?

**Comment by tasn** [comment]
Not really. Decryption speed is very fast, the performance penalty, if existent, should be minimal. If that's not the case, we can make sure to have a local index kept up to date or something. Though I really doubt performance would be a concern.
