### ISSUE TITLE
Formatting when using backticks for inline code is broken in webbrowsers

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/etesync-notes#9]
When using backticks to display inline code, the formatting "leaks" over into the lines below and above. 
This happens in browser (I tested both FF and chromium), but not in the Android app.

Example:
![image](https://user-images.githubusercontent.com/19950793/95310142-5639bc00-088c-11eb-85fc-babf05f0aa79.png)

**Comment by tasn** [comment]
Interesting, thanks, will have to take a look!
